### ISSUE TITLE
Enable to sort items by alphabetical order

### ISSUE THREAD

**Issue by tomodian** [instoll/tana-public-issues#24]
Kindly suggested by `LK2`, items is preferred to be sortable by alphabetical order.

## TODOs

- [ ] Add sorter button
- [ ] Enable to sort by `name (asc|desc)`, `created_by (asc|desc)`.
- [ ] Test in iOS / Android
- [ ] Release
